#!/bin/sh
#These are variables to pass to the job handler, see http://wiki.rc.ufl.edu/doc/Annotated_PBS_Script and
#http://wiki.rc.ufl.edu/doc/PBS_Directives for more details

#Do not rerun the job if it fails
#PBS -r n

#The name of the job
#PBS -N JOBNAME

#The file that output will be written to
#PBS -o JOBNAME.out

#The file that errors will be written to
#PBS -e JOBNAME.err

#Notifications options. a=notify when job is aborted, b=notify when job begins, e=notify when job terminates
#PBS -m abe

#Email to send notifications to
#PBS -M harris.d@ufl.edu

#These are the important ones, the amount of resources you want to use.
#Nodes are the number of seperate servers that you want to use. ppn is processors per node.
#Using more than 1 node requires your script to have cross server communication built into it, so for most work we'll
#probably just use single nodes.
#ppn should match the number of threads/cores you setup in your script. Our max for the lab at the moment is 32.
#PBS -l nodes=1:ppn=16

#The amount of memory that your script will require. This can be just a rough guess with some buffer added on.
#8192mb is a reasonable starting value, if you're not sure and you think your script could run on a laptop.
#PBS -l pmem=16384mb

#The length of time your script will run. again this can be a rough guess with some buffer time added.
#If your script goes over this amount of time it will be killed.
#PBS -l walltime=50:00:00

#Set the working directory of the job to your current working directory
cd $PBS_O_WORKDIR

#Loads R
module load R

#The actual command to run your script like you would from the command line.
Rscript "sdm.R"

